# docker compose file for the UTA load procedure

version: '3'

services:
  ncbi-download:
    image: uta-load
    command: sbin/ncbi-download /ncbi-dir
    volumes:
      - .:/opt/repos/uta
      - ${NCBI_DIR}:/ncbi-dir
    working_dir: /opt/repos/uta
    network_mode: host
  uta:
    container_name: uta
    image: biocommons/uta:${UTA_VERSION}
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: psql -h localhost -U anonymous -d uta -c "select * from ${UTA_VERSION}.meta"
      interval: 10s
      retries: 60
    network_mode: host
  uta-load:
    image: uta-load
    command: etc/scripts/uta-load ${UTA_VERSION} /ncbi-dir /uta-load/work /uta-load/logs
    depends_on:
      uta:
        condition: service_healthy
    volumes:
      - ${NCBI_DIR}:/ncbi-dir
      - ${SEQREPO_DIR}:/usr/local/share/seqrepo
      - ${WORKING_DIR}:/uta-load/work
      - ${LOG_DIR}:/uta-load/logs
    network_mode: host
