version: '3'

services:
  uta:
    container_name: uta
    image: biocommons/uta:${UTA_ETL_OLD_UTA_IMAGE_TAG}
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: psql -h localhost -U anonymous -d uta -c "select * from ${UTA_ETL_OLD_UTA_IMAGE_TAG}.meta"
      interval: 10s
      retries: 80
    network_mode: host
  uta-check-transcripts:
    image: uta-update
    command: sbin/uta-check-transcripts ${UTA_ETL_OLD_UTA_VERSION} /uta-check-transcripts/work /uta-check-transcripts/logs
    depends_on:
      uta:
        condition: service_healthy
    volumes:
      - ${UTA_ETL_WORK_DIR}:/uta-check-transcripts/work
      - ${UTA_ETL_LOG_DIR}:/uta-check-transcripts/logs
    network_mode: host
