# base docker compose file for the UTA update procedure

version: '3'

services:
  seqrepo-pull:
    user: root
    image: uta-update
    command: sbin/seqrepo-pull
    volumes:
      - seqrepo-volume:/biocommons/dl.biocommons.org/seqrepo
  ncbi-download:
    image: uta-update
    environment:
      - DOWNLOAD_DIR=/ncbi-dir
    command: sbin/ncbi-download etc/ncbi-files.txt
    volumes:
      - .:/opt/repos/uta
      - ${UTA_ETL_NCBI_DIR}:/ncbi-dir
    working_dir: /opt/repos/uta
  uta-extract:
    image: uta-update
    environment:
      - NCBI_DIR=/ncbi-dir
      - WORKING_DIR=/uta-extract/work
      - LOG_DIR=/uta-extract/logs
    command: sbin/uta-extract
    volumes:
      - ${UTA_ETL_NCBI_DIR}:/ncbi-dir
      - ${UTA_ETL_WORK_DIR}:/uta-extract/work
      - ${UTA_ETL_LOG_DIR}:/uta-extract/logs
    working_dir: /opt/repos/uta
  seqrepo-load:
    image: uta-update
    environment:
      - SEQUENCE_DIR=/seqrepo-load/work
      - LOG_DIR=/seqrepo-load/logs
    command: sbin/seqrepo-load
    volumes:
      - seqrepo-volume:/biocommons/dl.biocommons.org/seqrepo
      - ${UTA_ETL_WORK_DIR}:/seqrepo-load/work
      - ${UTA_ETL_LOG_DIR}:/seqrepo-load/logs
    working_dir: /opt/repos/uta
  uta-load:
    image: uta-update
    environment:
      - NCBI_DIR=/ncbi-dir
      - WORKING_DIR=/uta-load/work
      - LOG_DIR=/uta-load/logs
    command: sbin/uta-load ${UTA_ETL_OLD_UTA_VERSION} ${UTA_ETL_NEW_UTA_VERSION}
    volumes:
      - ${UTA_ETL_WORK_DIR}:/uta-load/work
      - ${UTA_ETL_LOG_DIR}:/uta-load/logs

volumes:
  seqrepo-volume:
