#!/usr/bin/env bash

# This script runs ncbi-download in a docker container.

# param will be checked in the ncbi-download script
DOWNLOAD_DIR=$1

if [ -z "$DOWNLOAD_DIR" ]
then
    echo 'Usage: sbin/ncbi-download-docker <download_dir>'
    exit 1
else
    echo "Downloading files to $DOWNLOAD_DIR"
fi

docker build --file $(pwd)/misc/docker/ncbi-download.dockerfile --tag ncbi-download --progress plain .
docker run -it -v $(pwd)/sbin/ncbi-download:/dl-script -v $DOWNLOAD_DIR:/output-dir ncbi-download /dl-script /output-dir
