#!/usr/bin/env bash

set -euxo pipefail

if [ -z "$SEQUENCE_DIR" ] || [ -z "$LOG_DIR" ]
then
    echo 'SEQUENCE_DIR and LOG_DIR environment variables must be set.'
    exit 1
fi

# find all fasta files in the working directory
mapfile -t FASTA_FILES < <(find "$SEQUENCE_DIR" -type f -name "*.f[an]a*")

# Load SeqRepo with new sequences
seqrepo --root-directory "/biocommons/dl.biocommons.org/seqrepo" \
    load -n NCBI --instance-name "master" \
    "${FASTA_FILES[@]}" 2>&1 | \
    tee "$LOG_DIR/seqrepo-load.log"
