#!/usr/bin/env bash

set -e

seqrepo_root=$1
seqrepo_version=$2
sequence_dir=$3
logs_dir=$4

if [ -z "$seqrepo_root" ] || [ -z "$seqrepo_version" ] || [ -z "$sequence_dir" ] || [ -z "$logs_dir" ]
then
    echo 'Usage: sbin/seqrepo-load <seqrepo_root> <seqrepo_version> <sequence_dir> <logs_dir>'
    exit 1
fi

## Load SeqRepo with new sequences
seqrepo --root-directory "$seqrepo_root" \
    load -n NCBI --instance-name "$seqrepo_version" \
    $sequence_dir/*.fna.gz \
    $sequence_dir/*.faa.gz 2>& 1 | \
    tee "$logs_dir/seqrepo-load.log"
