#!/usr/bin/env bash

# This script updates the specified UTA and SeqRepo using the given NCBI files.
# It produces a postgres dump of the updated UTA database and an updated SeqRepo (updated in place).
# It expects to be run from the root of the uta repository.

set -e

NCBI_FILE_DIR=$1
SEQREPO_DIR=$2
UTA_VERSION=$3
SEQREPO_VERSION=$4

if [ -z "$NCBI_FILE_DIR" ] || [ -z "$SEQREPO_DIR" ] || [ -z "$UTA_VERSION" ] || [ -z "$SEQREPO_VERSION" ]
then
    echo 'Usage: sbin/update-uta <ncbi_file_dir> <seqrepo_dir> <uta_version> <seqrepo_version>'
    exit 1
else
    echo "Updating UTA and SeqRepo using files from $NCBI_FILE_DIR and SeqRepo data in $SEQREPO_DIR"
    echo "Starting from UTA version $UTA_VERSION and SeqRepo version $SEQREPO_VERSION"
fi

if [[ $NCBI_FILE_DIR != /* ]] && [[ $NCBI_FILE_DIR != .* ]]
then
    echo 'NCBI file directory must start with / or .'
    exit 1
fi

if [[ $SEQREPO_DIR != /* ]] && [[ $SEQREPO_DIR != .* ]]
then
    echo 'SeqRepo data directory must start with / or .'
    exit 1
fi

ncbi_files=$NCBI_FILE_DIR seqrepo_dir=$SEQREPO_DIR seqrepo_version=$SEQREPO_VERSION uta_version=$UTA_VERSION \
    docker compose -f docker-compose.uta-update.yml run --rm --name uta-update uta-update

docker compose -f docker-compose.uta.yml down
