#!/usr/bin/env bash

# This script updates UTA and SeqRepo using NCBI files.
# source_uta_v is the UTA version before the update.
# ncbi_dir is where the script looks for NCBI data files.
# working_dir stores intermediate data files and the final database dump.
# log_dir stores log files.

# Note that the uta loading code uses the seqrepo location defined in the conf files, under [sequences].seqrepo.

set -euxo pipefail

source_uta_v=$1
dest_uta_v=$2
config_file=$3

if [ -z "$source_uta_v" ] || [ -z "$dest_uta_v" ] || [ -z "$config_file" ]
then
    echo 'Usage: uta-load <source_uta_v> <dest_uta_v> <config_file>'
    exit 1
fi

if [ -z "$DB_HOST" ] || [ -z "$WORKING_DIR" ] || [ -z "$LOG_DIR" ]
then
    echo 'Please set DB_HOST, WORKING_DIR and LOG_DIR environment variables.'
    exit 1
fi

# set local variables and create working directories
loading_uta_v="uta"

## Drop loading schema, and recreate
sbin/create-new-schema.sh "$source_uta_v" "$loading_uta_v"

## for now set up Alembic for schema migrations
alembic -c etc/alembic.ini upgrade head

# generate seqinfo files from exonsets (this step requires seqrepo)
sbin/exonset-to-seqinfo -o NCBI "$WORKING_DIR/exonsets.gz" | gzip -c > "$WORKING_DIR/seqinfo.gz" 2>&1 | \
    tee "$LOG_DIR/exonset-to-seqinfo.log"

# Filter out columns from assocacs file.
sbin/assoc-acs-merge "$WORKING_DIR/assocacs.gz" | gzip -c > "$WORKING_DIR/assoc-ac.gz" 2>&1 | \
    tee "$LOG_DIR/assoc-acs-merge.log"

# Load genes into gene table.
uta --conf=etc/global.conf --conf="$config_file" load-geneinfo "$WORKING_DIR/geneinfo.gz" 2>&1 | \
    tee "$LOG_DIR/load-geneinfo.log"

# Load accessions into associated_accessions table.
uta --conf=etc/global.conf --conf="$config_file" load-assoc-ac "$WORKING_DIR/assoc-ac.gz" 2>&1 | \
    tee "$LOG_DIR/load-assoc-ac.log"

# Load transcript info into transcript and exon_set tables.
uta --conf=etc/global.conf --conf="$config_file" load-txinfo "$WORKING_DIR/txinfo.gz" 2>&1 | \
    tee "$LOG_DIR/load-txinfo.log"

# Load exon sets into into exon_set and exon tables.
uta --conf=etc/global.conf --conf="$config_file" load-exonset "$WORKING_DIR/exonsets.gz" 2>&1 | \
    tee "$LOG_DIR/load-exonsets.log"

# Load seqinfo into the seq and seqanno tables.
uta --conf=etc/global.conf --conf="$config_file" load-seqinfo "$WORKING_DIR/seqinfo.gz" 2>&1 | \
    tee "$LOG_DIR/load-seqinfo.log"

# Create cigar strings for all rows in tx_alt_exon_pairs_v view and update exon_aln table.
uta --conf=etc/global.conf --conf="$config_file" align-exons 2>&1 | \
    tee "$LOG_DIR/align-exons.log"

### run diff
sbin/uta-diff "$source_uta_v" "$loading_uta_v"

## Rename schema to destination schema name and export to dump file
psql -h "$DB_HOST" -U uta_admin -d uta -c "DROP SCHEMA IF EXISTS $dest_uta_v CASCADE;"
psql -h "$DB_HOST" -U uta_admin -d uta -c "ALTER SCHEMA uta RENAME TO $dest_uta_v";
pg_dump -h "$DB_HOST" -U uta_admin -d uta -n "$dest_uta_v" | \
 gzip -c > "$WORKING_DIR/$dest_uta_v.pgd.gz"
