#!/usr/bin/env bash

# This script runs the UTA update procedure.
# It expects to be run from the root of the uta repository.
# It updates the specified UTA and SeqRepo using the given NCBI files.
# The UTA update is provided as a postgres database dump, and SeqRepo is updated in place.

set -e

# export environment variables for docker compose file
export NCBI_DIR=$1
export SEQREPO_DIR=$2
export UTA_VERSION=$3
export WORKING_DIR=$4
export LOG_DIR=$4

if [ -z "$NCBI_DIR" ] || [ -z "$SEQREPO_DIR" ] || [ -z "$UTA_VERSION" ] || [ -z "$WORKING_DIR" ] || [ -z "$LOG_DIR" ]
then
    echo 'Usage: sbin/uta-load <ncbi_file_dir> <seqrepo_dir> <uta_version> <output_dir> <log_dir>'
    exit 1
else
    echo "Updating UTA and SeqRepo using files in $NCBI_DIR and SeqRepo data in $SEQREPO_DIR"
    echo "Starting from UTA version $UTA_VERSION"
    echo "Final dump and any intermediate files will be available in $WORKING_DIR"
    echo "Logs will be available in $LOG_DIR"
fi

# Ensure directories are compatible with docker volume usage
if [[ $NCBI_DIR != /* ]] && [[ $NCBI_DIR != .* ]]
then
    echo 'NCBI file directory must start with / or .'
    exit 1
fi

if [[ $SEQREPO_DIR != /* ]] && [[ $SEQREPO_DIR != .* ]]
then
    echo 'SeqRepo data directory must start with / or .'
    exit 1
fi

if [[ $WORKING_DIR != /* ]] && [[ $WORKING_DIR != .* ]]
then
    echo 'Output directory must start with / or .'
    exit 1
fi

if [[ $LOG_DIR != /* ]] && [[ $LOG_DIR != .* ]]
then
    echo 'Log directory must start with / or .'
    exit 1
fi

# Ensure directories exist.
if [ ! -d "$NCBI_DIR" ]; then
    echo "Directory $NCBI_DIR does not exist."
    exit 1
fi

if [ ! -d "$SEQREPO_DIR" ]; then
    echo "Directory $SEQREPO_DIR does not exist."
    exit 1
fi

if [ ! -d "$WORKING_DIR" ]; then
    echo "Directory $WORKING_DIR does not exist."
    exit 1
fi

if [ ! -d "$LOG_DIR" ]; then
    echo "Directory $LOG_DIR does not exist."
    exit 1
fi

# Build the UTA image.
docker build --target uta -t uta-load .

# Bring up a UTA database and run the UTA load procedure.
# docker compose doesn't respect the container name specified in the compose file, so container name is specified here
docker compose run --rm --name uta-load uta-load
