"""add SqlAlchemy model for associated_accessions

Revision ID: 9c0ee2eb9be8
Revises: edadb97f6502
Create Date: 2024-04-04 01:47:48.149237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c0ee2eb9be8'
down_revision: Union[str, None] = 'edadb97f6502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('associated_accessions', 'tx_ac',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='uta')
    op.alter_column('associated_accessions', 'pro_ac',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='uta')
    op.alter_column('associated_accessions', 'added',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='uta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('associated_accessions', 'added',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='uta')
    op.alter_column('associated_accessions', 'pro_ac',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='uta')
    op.alter_column('associated_accessions', 'tx_ac',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='uta')
    # ### end Alembic commands ###
