"""sync database with models

Revision ID: af089519b0ee
Revises: 1b8f087cc856
Create Date: 2024-04-03 02:08:16.163939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af089519b0ee'
down_revision: Union[str, None] = '1b8f087cc856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('associated_accessions', 'tx_ac',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='uta_1_1')
    op.alter_column('associated_accessions', 'pro_ac',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='uta_1_1')
    op.alter_column('associated_accessions', 'added',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='uta_1_1')
    op.drop_table_comment(
        'associated_accessions',
        existing_comment='transcript-protein accession pairs associated in source databases',
        schema='uta_1_1'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'associated_accessions',
        'transcript-protein accession pairs associated in source databases',
        existing_comment=None,
        schema='uta_1_1'
    )
    op.alter_column('associated_accessions', 'added',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='uta_1_1')
    op.alter_column('associated_accessions', 'pro_ac',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='uta_1_1')
    op.alter_column('associated_accessions', 'tx_ac',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='uta_1_1')
    # ### end Alembic commands ###
