version: '3'

services:
  seqrepo:
    container_name: seqrepo
    image: ubuntu:latest
    command: echo 'Start SeqRepo, which is required for UTA update'
    networks:
      - uta-sr-net
  uta-update:
    container_name: uta-update
    image: uta-update:latest
    # todo: use command from uta container
    command: etc/scripts/run-uta-build.sh previous-uta ${previous_uta_version}
    depends_on:
      previous-uta:
        condition: service_healthy
      # seqrepo:
      #   condition: service_healthy
    volumes:
      - ./ncbi:/temp
    networks:
      - uta-sr-net
  previous-uta:
    container_name: previous-uta
    image: uta:${previous_uta_version}
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: pg_isready && psql -h localhost -U anonymous -d uta -c "select * from ${previous_uta_version}.meta"
      interval: 10s
      retries: 60
    networks:
      - uta-sr-net

networks:
  uta-sr-net:
