version: '3'

services:
  seqrepo:
    container_name: seqrepo
    image: ubuntu:latest
    command: echo 'Start SeqRepo, which is required for UTA update'
    networks:
      - uta-sr-net
  uta-update:
    container_name: uta-update
    image: ubuntu:latest
    # todo: use command from uta container
    command: ls /data/ncbi
    depends_on:
      previous-uta:
        condition: service_healthy
      # seqrepo:
      #   condition: service_healthy
    volumes:
      - ./ncbi:/data/ncbi
    networks:
      - uta-sr-net
  previous-uta:
    container_name: previous-uta
    image: biocommons/uta:${previous_uta_version}
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: pg_isready && psql -h localhost -U anonymous -d uta -c "select * from ${previous_uta_version}.meta"
      interval: 10s
      retries: 60
    networks:
      - uta-sr-net

networks:
  uta-sr-net:
